### PR TITLE
Handle next bowl after spare and add tests for strikes

### PR DESCRIPTION
**Pull request by dtcoutu**
Had a significant amount of refactoring after the initial hack of a solution.  I'd suggest looking at each commit and seeing if they seem a good break down of things to you.

Some thoughts:
- Wanted `update()` to score the spare, but couldn't find a good path to it...yet.  I even considered building up the score each time instead of maintaining it.  In then end we should discuss that more.
- Also, should we score a spare Frame as soon as the next ball is thrown or always wait until the next Frame is done being bowled?
- I don't like the `firstBowl()` method.  Since we should add the next ball after a spare it seems we should ask the `Scoreboard` for the next ball for a given Frame?
- Optional is noisier than I'd like, but I think it's the right choice - just might need a better pattern for use.
- LinkedList works, but typically ArrayList is used - consider [this analysis](https://stackoverflow.com/questions/322715/when-to-use-linkedlist-over-arraylist#322742) of them (though realize that it's not that big of deal in our case)

### CODE REVIEW

**Comment by jociemoore** [comment]
I followed your thinking. A couple things:
- I think using LinkedList was a mistake on my part. Thinking back, I believe I chose it here because I was incorrectly remembering working with a HashMap and wanting the retrieval of key/values to be in the same order they were inserted. In this previous situation I should have chose LinkedHashMap, and I confused that situation with List. Nonetheless, that article was a good reminder of the specific advantages of LinkedList and ArrayList: LinkedList is more efficient for inserting values mid-list and ArrayList is more efficient for retrieving values (which really doesn't matter in our case because our list is only ever going to hold 10 Frames).

- I have never worked with Optional before. Seems straightforward I think. Is the alternative to deal with the `IndexOutOfBoundsException` you would get if calling `get()` on an ArrayList?

- Lastly, (this is small) is there a specific reason why `updateTotalPoints()` within the `Scoreboard` class has two different if statements rather than an if/else statement?

I plan to merge your changes and work on the next two tests during lunch today.

**Comment by dtcoutu** [comment]
Working with the `IndexOutOfBoundsException` is one way, but given how it was written I was already checking if the index was valid.  If it wasn't a `null` would've been returned instead of the `Optional`, so we'd have to check if it was null.  Not really a gain, but we might be able to make use of more functional flows in the future which will help clean that up.

`updateTotalPoints()` has two ifs because I thought of them as two independent steps.  Regardless of the state of the current frame - if it's a spare or not - we should check the previous frame to see if it was a spare and needed to be updated.

**Comment by jociemoore** [comment]
yes, yes! I should have been able to grasp that about `updateTotalPoints()`.

Yesterday was kind of a waste. I ran into issues doing `git pull` at DDC. I'm not sure why, but when my lunch hour was up I was reading something related to SSH keys. Anyways, once I got home it worked fine -- I should have just switched back to my work computer earlier.

So I have the strike test working and now I'm refactoring. Some of the points you raised when you created your last pull request seem dependent and/or perhaps a non-issue depending on which way we go with how we want to deal with the score. I'm curious why you want the `update()` method in `Scoreboard` to score spare. For me, I've been thinking of `update()` a way of managing and advancing frames. In this light, I liked your idea of removing `updateTotalPoints()` and putting that logic into something like `calculateScore()', which would remove the need to maintain the score and remove anything score related from `update()`.

Is this good thinking? What other factors were you weighing?

**Comment by dtcoutu** [comment]
Perhaps I'm wanting to give `update()` too much authority, but I liked the idea that getting the ball would be able to update the current frame and any previous that cared about it.  For instance, if the frame is a spare it will score itself and the next ball.  That means that it would have to know about the next frame - which because a bit of a hurdle.  Would we want to have the frames know about their neighbors.  (I can also see it getting more complex when we're trying to work with a strike.)

So, I'm really just reacting to feeling like I need to figure out the current frame, then the previous.  I think `calculatingScore()` could be good - though it trades off on having the score immediately available.  It might be worth it having both of the method around to see how things flow for each of them.

**Pull request merged**
